
import { Member, Transaction, ChurchEvent, Payroll, FinancialAccount, AuditLog, TaxConfig, Unit, Asset, EmployeeLeave } from './types';

export const MOCK_UNITS: Unit[] = [
  { id: 'u-sede', name: 'ADJPA - Sede Mundial', cnpj: '00.123.456/0001-99', address: 'Rua das Nações, 1000', city: 'São Paulo', state: 'SP', isHeadquarter: true },
  { id: 'u-filial1', name: 'ADJPA - Unidade Leste', cnpj: '00.123.456/0002-88', address: 'Av. Brasil, 500', city: 'São Paulo', state: 'SP', isHeadquarter: false },
];

export const MOCK_ASSETS: Asset[] = [
  { 
    id: 'ast1', 
    unitId: 'u-sede', 
    description: 'Imóvel Sede Mundial', 
    category: 'IMÓVEL', 
    acquisitionDate: '2010-01-15', 
    acquisitionValue: 2500000, 
    currentValue: 3800000, 
    depreciationRate: 0, 
    location: 'Templo Principal', 
    condition: 'BOM', 
    assetNumber: 'AD-0001' 
  },
  { 
    id: 'ast2', 
    unitId: 'u-sede', 
    description: 'Console Digital Behringer X32', 
    category: 'SOM_LUZ', 
    acquisitionDate: '2022-03-10', 
    acquisitionValue: 18500, 
    currentValue: 15000, 
    depreciationRate: 10, 
    location: 'Cabine de Som', 
    condition: 'NOVO', 
    assetNumber: 'AD-0042' 
  },
];

export const MOCK_LEAVES: EmployeeLeave[] = [
  {
    id: 'lv1',
    unitId: 'u-sede',
    employeeId: 'p1',
    employeeName: 'Ricardo Oliveira Ramos',
    type: 'VACATION',
    startDate: '2024-06-01',
    endDate: '2024-06-30',
    status: 'SCHEDULED',
    observations: 'Férias regulares período 23/24'
  }
];

export const OPERATION_NATURES = [
  { id: 'nat1', name: 'Despesa Operacional' },
  { id: 'nat2', name: 'Investimento / Ativo Imobilizado' },
  { id: 'nat3', name: 'Impostos e Contribuições' },
  { id: 'nat4', name: 'Transferências entre Contas' },
  { id: 'nat5', name: 'Ajuste de Saldo / Correção' },
  { id: 'nat6', name: 'Receita Ordinária' },
  { id: 'nat7', name: 'Receita Extraordinária' },
];

export const CHURCH_PROJECTS = [
  { id: 'prj1', name: 'Reforma do Santuário 2024' },
  { id: 'prj2', name: 'Congresso Geral de Missões' },
  { id: 'prj3', name: 'Aquisição de Novos Equipamentos Som' },
  { id: 'prj4', name: 'Projeto Social Mãos Amigas' },
];

export const COST_CENTERS = [
  { id: 'cc1', name: 'Administrativo' },
  { id: 'cc2', name: 'Missões e Evangelismo' },
  { id: 'cc3', name: 'Ministério Infantil' },
  { id: 'cc4', name: 'Ministério de Louvor' },
  { id: 'cc5', name: 'Patrimônio / Obras' },
  { id: 'cc6', name: 'Ação Social' },
  { id: 'cc7', name: 'Educação Teológica' },
];

export const DEFAULT_TAX_CONFIG: TaxConfig = {
  inssBrackets: [
    { limit: 1412.00, rate: 0.075 },
    { limit: 2666.68, rate: 0.090 },
    { limit: 4000.03, rate: 0.120 },
    { limit: 7786.02, rate: 0.140 }
  ],
  irrfBrackets: [
    { limit: 2259.20, rate: 0.000, deduction: 0.00 },
    { limit: 2826.65, rate: 0.075, deduction: 169.44 },
    { limit: 3751.05, rate: 0.150, deduction: 381.44 },
    { limit: 4664.68, rate: 0.225, deduction: 662.77 },
    { limit: Infinity, rate: 0.275, deduction: 896.00 }
  ],
  fgtsRate: 0.08,
  patronalRate: 0.20,
  ratRate: 0.03 
};

export const MOCK_ACCOUNTS: FinancialAccount[] = [
  { id: 'acc1', unitId: 'u-sede', name: 'Caixa Sede', type: 'CASH', currentBalance: 9650.00 },
  { id: 'acc2', unitId: 'u-sede', name: 'Bradesco - Geral', type: 'BANK', currentBalance: 80095.00 },
  { id: 'acc3', unitId: 'u-filial1', name: 'Itaú - Construção', type: 'BANK', currentBalance: 102080.00 },
];

export const MOCK_MEMBERS: Member[] = [
  { 
    id: '1', 
    unitId: 'u-sede',
    name: 'João Silva', 
    cpf: '123.456.789-00',
    rg: '12.345.678-9',
    email: 'joao@email.com', 
    phone: '(11) 98888-7777',
    whatsapp: '(11) 98888-7777',
    profession: 'Engenheiro Civil',
    role: 'MEMBER', 
    status: 'ACTIVE', 
    birthDate: '1985-05-15',
    gender: 'M',
    maritalStatus: 'MARRIED',
    conversionDate: '2010-03-20',
    baptismDate: '2010-06-15',
    isTithable: true,
    isRegularGiver: true,
    participatesCampaigns: false,
    contributions: [
      { id: 'c1', value: 500, date: '2024-05-01', type: 'TITHE' },
      { id: 'c2', value: 450, date: '2024-04-02', type: 'TITHE' },
      { id: 'c3', value: 50, date: '2024-04-15', type: 'OFFERING' }
    ],
    address: {
      zipCode: '01234-567',
      street: 'Rua das Flores',
      number: '123',
      neighborhood: 'Jardim Primavera',
      city: 'São Paulo',
      state: 'SP'
    },
    avatar: 'https://i.pravatar.cc/150?u=1' 
  },
  { 
    id: '2', 
    unitId: 'u-filial1',
    name: 'Maria Oliveira', 
    cpf: '987.654.321-11',
    rg: '22.333.444-5',
    email: 'maria@email.com', 
    phone: '(11) 97777-6666',
    role: 'MEMBER', 
    status: 'ACTIVE', 
    birthDate: '1992-08-20',
    gender: 'F',
    maritalStatus: 'SINGLE',
    isTithable: true,
    isRegularGiver: false,
    participatesCampaigns: true,
    contributions: [],
    address: { zipCode: '04567-890', street: 'Av. Paulista', number: '1000', neighborhood: 'Bela Vista', city: 'São Paulo', state: 'SP' },
    avatar: 'https://i.pravatar.cc/150?u=2' 
  },
  { 
    id: '3', 
    unitId: 'u-sede',
    name: 'Carlos Alberto', 
    cpf: '444.555.666-77',
    rg: '11.222.333-4',
    email: 'carlos@email.com', 
    phone: '(11) 96666-5555',
    role: 'VISITOR', 
    status: 'ACTIVE', 
    birthDate: '1980-01-10',
    gender: 'M',
    maritalStatus: 'DIVORCED',
    isTithable: false,
    isRegularGiver: false,
    participatesCampaigns: false,
    contributions: [],
    address: { zipCode: '01234-567', street: 'Rua das Palmeiras', number: '45', neighborhood: 'Centro', city: 'São Paulo', state: 'SP' },
    avatar: 'https://i.pravatar.cc/150?u=3' 
  },
  { 
    id: '4', 
    unitId: 'u-sede',
    name: 'Ana Paula Martins', 
    cpf: '111.222.333-44',
    rg: '44.555.666-7',
    email: 'ana.martins@email.com', 
    phone: '(11) 91234-5678',
    whatsapp: '(11) 91234-5678',
    profession: 'Analista Financeira',
    role: 'LEADER', 
    status: 'ACTIVE', 
    birthDate: '1990-09-12',
    gender: 'F',
    maritalStatus: 'MARRIED',
    conversionDate: '2008-04-10',
    baptismDate: '2008-06-01',
    isTithable: true,
    isRegularGiver: true,
    participatesCampaigns: true,
    contributions: [
      { id: 'c4a', value: 650, date: '2024-05-03', type: 'TITHE' },
      { id: 'c4b', value: 100, date: '2024-05-19', type: 'OFFERING' }
    ],
    address: { zipCode: '01310-000', street: 'Rua Augusta', number: '250', neighborhood: 'Consolação', city: 'São Paulo', state: 'SP' },
    avatar: 'https://i.pravatar.cc/150?u=4' 
  },
  { 
    id: '5', 
    unitId: 'u-filial1',
    name: 'Bruno Henrique Souza', 
    cpf: '555.666.777-88',
    rg: '55.666.777-8',
    email: 'bruno.souza@email.com', 
    phone: '(11) 93456-7890',
    role: 'VOLUNTEER', 
    status: 'ACTIVE', 
    birthDate: '1998-04-22',
    gender: 'M',
    maritalStatus: 'SINGLE',
    isTithable: true,
    isRegularGiver: false,
    participatesCampaigns: true,
    contributions: [
      { id: 'c5a', value: 120, date: '2024-04-07', type: 'OFFERING' }
    ],
    address: { zipCode: '08090-200', street: 'Rua Itaquera', number: '800', neighborhood: 'Leste', city: 'São Paulo', state: 'SP' },
    avatar: 'https://i.pravatar.cc/150?u=5' 
  },
  { 
    id: '6', 
    unitId: 'u-sede',
    name: 'Fernanda Carvalho', 
    cpf: '666.777.888-99',
    rg: '66.777.888-9',
    email: 'fernanda.carvalho@email.com', 
    phone: '(11) 94567-1234',
    role: 'MEMBER', 
    status: 'ACTIVE', 
    birthDate: '1987-12-05',
    gender: 'F',
    maritalStatus: 'DIVORCED',
    isTithable: true,
    isRegularGiver: true,
    participatesCampaigns: false,
    contributions: [
      { id: 'c6a', value: 400, date: '2024-05-08', type: 'TITHE' }
    ],
    address: { zipCode: '04004-020', street: 'Rua Domingos de Morais', number: '1500', neighborhood: 'Vila Mariana', city: 'São Paulo', state: 'SP' },
    avatar: 'https://i.pravatar.cc/150?u=6' 
  }
];

export const MOCK_PAYROLL: Payroll[] = [
  { 
    id: 'p1', 
    unitId: 'u-sede',
    matricula: '2024001', 
    employeeName: 'Ricardo Oliveira Ramos', 
    cpf: '222.333.444-55',
    rg: '22.333.444-5',
    pis: '120.44556.77-8',
    ctps: '0054321/0001',
    cargo: 'Pastor Auxiliar',
    funcao: 'Ministério Pastoral',
    departamento: 'Eclesiástico',
    cbo: '2631-05',
    data_admissao: '2021-01-10',
    birthDate: '1978-08-22',
    tipo_contrato: 'CLT',
    jornada_trabalho: '44h semanais',
    regime_trabalho: 'PRESENCIAL',
    salario_base: 4500,
    tipo_salario: 'MENSAL',
    he50_qtd: 10,
    he100_qtd: 0,
    dsr_ativo: true,
    adic_noturno_qtd: 0,
    insalubridade_grau: 'NONE',
    periculosidade_ativo: false,
    comissoes: 0,
    gratificacoes: 500,
    premios: 0,
    ats_percentual: 5,
    auxilio_moradia: 800,
    arredondamento: 0,
    dependentes_qtd: 2,
    dependentes_lista: [
      { id: 'd1', name: 'Enzo Oliveira', birthDate: '2018-05-20', relationship: 'FILHO', cpf: '999.888.777-66' },
      { id: 'd1b', name: 'Beatriz Oliveira', birthDate: '2020-03-12', relationship: 'FILHO', cpf: '999.777.666-55' }
    ],
    is_pcd: false,
    tipo_deficiencia: '',
    blood_type: 'O+',
    emergency_contact: '(11) 98877-6655 (Esposa)',
    vt_ativo: true,
    vale_transporte_total: 220,
    va_ativo: true,
    vale_alimentacao: 600,
    vr_ativo: false,
    vale_refeicao: 0,
    ps_ativo: true,
    plano_saude_colaborador: 420,
    po_ativo: false,
    plano_saude_dependentes: 0,
    vale_farmacia: 0,
    seguro_vida: 25,
    banco: 'Itaú',
    codigo_banco: '341',
    agencia: '0101',
    conta: '12345-6',
    tipo_conta: 'CORRENTE',
    titular: 'Ricardo Oliveira Ramos',
    chave_pix: 'ricardo@pastoral.com',
    month: '05',
    year: '2024',
    faltas: 0,
    atrasos: 0,
    adiantamento: 0,
    pensao_alimenticia: 0,
    consignado: 0,
    outros_descontos: 0,
    coparticipacoes: 0,
    inss: 480.50,
    fgts_retido: 400,
    irrf: 245.30,
    fgts_patronal: 400,
    inss_patronal: 1150,
    rat: 150,
    terceiros: 150,
    total_proventos: 5000,
    total_descontos: 725.80,
    salario_liquido: 4274.20,
    status: 'ACTIVE',
    cnh_numero: '12345678901',
    cnh_categoria: 'B',
    cnh_vencimento: '2025-05-15',
    address: {
      zipCode: '01234-567',
      street: 'Rua das Flores',
      number: '123',
      neighborhood: 'Jardim Primavera',
      city: 'São Paulo',
      state: 'SP'
    }
  },
  { 
    id: 'p2', 
    unitId: 'u-sede',
    matricula: '2024002', 
    employeeName: 'Juliana Mendes Santana', 
    cpf: '333.444.555-66',
    rg: '33.444.555-6',
    pis: '130.55667.88-9',
    ctps: '0065432/0002',
    cargo: 'Secretária Administrativa',
    funcao: 'Secretariado',
    departamento: 'Administrativo',
    cbo: '4110-05',
    data_admissao: '2022-03-15',
    birthDate: '1995-11-30',
    tipo_contrato: 'CLT',
    jornada_trabalho: '44h semanais',
    regime_trabalho: 'PRESENCIAL',
    salario_base: 2800,
    tipo_salario: 'MENSAL',
    he50_qtd: 0,
    he100_qtd: 0,
    dsr_ativo: true,
    adic_noturno_qtd: 0,
    insalubridade_grau: 'NONE',
    periculosidade_ativo: false,
    comissoes: 0,
    gratificacoes: 0,
    premios: 0,
    ats_percentual: 2,
    auxilio_moradia: 0,
    arredondamento: 0,
    dependentes_qtd: 0,
    dependentes_lista: [],
    is_pcd: false,
    tipo_deficiencia: '',
    blood_type: 'A+',
    emergency_contact: '(11) 97766-5544 (Mãe)',
    vt_ativo: true,
    vale_transporte_total: 180,
    va_ativo: true,
    vale_alimentacao: 500,
    vr_ativo: true,
    vale_refeicao: 350,
    ps_ativo: true,
    plano_saude_colaborador: 280,
    po_ativo: false,
    plano_saude_dependentes: 0,
    vale_farmacia: 50,
    seguro_vida: 20,
    banco: 'Bradesco',
    codigo_banco: '237',
    agencia: '1234',
    conta: '54321-0',
    tipo_conta: 'CORRENTE',
    titular: 'Juliana Mendes Santana',
    chave_pix: '333.444.555-66',
    month: '05',
    year: '2024',
    faltas: 0,
    atrasos: 0,
    adiantamento: 0,
    pensao_alimenticia: 0,
    consignado: 0,
    outros_descontos: 0,
    coparticipacoes: 0,
    inss: 250.00,
    fgts_retido: 224,
    irrf: 0,
    fgts_patronal: 224,
    inss_patronal: 560,
    rat: 84,
    terceiros: 84,
    total_proventos: 2856,
    total_descontos: 250,
    salario_liquido: 2606,
    status: 'ACTIVE',
    address: {
      zipCode: '04567-890',
      street: 'Av. Paulista',
      number: '500',
      neighborhood: 'Bela Vista',
      city: 'São Paulo',
      state: 'SP'
    }
  },
  { 
    id: 'p3', 
    unitId: 'u-sede',
    matricula: '2024003', 
    employeeName: 'Ana Paula Martins', 
    cpf: '111.222.333-44',
    rg: '44.555.666-7',
    pis: '140.66778.99-0',
    ctps: '0076543/0003',
    cargo: 'Tesoureira',
    funcao: 'Financeiro',
    departamento: 'Administrativo',
    cbo: '2523-05',
    data_admissao: '2020-07-01',
    birthDate: '1990-09-12',
    tipo_contrato: 'CLT',
    jornada_trabalho: '40h semanais',
    regime_trabalho: 'HIBRIDO',
    salario_base: 5200,
    tipo_salario: 'MENSAL',
    he50_qtd: 0,
    he100_qtd: 0,
    dsr_ativo: true,
    adic_noturno_qtd: 0,
    insalubridade_grau: 'NONE',
    periculosidade_ativo: false,
    comissoes: 0,
    gratificacoes: 300,
    premios: 0,
    ats_percentual: 3,
    auxilio_moradia: 0,
    arredondamento: 0,
    dependentes_qtd: 1,
    dependentes_lista: [
      { id: 'd3a', name: 'Lucas Martins', birthDate: '2016-02-18', relationship: 'FILHO', cpf: '888.777.666-55' }
    ],
    is_pcd: false,
    tipo_deficiencia: '',
    blood_type: 'B+',
    emergency_contact: '(11) 90000-1234 (Esposo)',
    vt_ativo: true,
    vale_transporte_total: 200,
    va_ativo: true,
    vale_alimentacao: 650,
    vr_ativo: true,
    vale_refeicao: 400,
    ps_ativo: true,
    plano_saude_colaborador: 350,
    po_ativo: false,
    plano_saude_dependentes: 0,
    vale_farmacia: 60,
    seguro_vida: 30,
    banco: 'Itaú',
    codigo_banco: '341',
    agencia: '0202',
    conta: '23456-7',
    tipo_conta: 'CORRENTE',
    titular: 'Ana Paula Martins',
    chave_pix: 'ana.financeiro@adjpa.org',
    month: '05',
    year: '2024',
    faltas: 0,
    atrasos: 0,
    adiantamento: 0,
    pensao_alimenticia: 0,
    consignado: 0,
    outros_descontos: 0,
    coparticipacoes: 0,
    inss: 600.00,
    fgts_retido: 416,
    irrf: 120.00,
    fgts_patronal: 416,
    inss_patronal: 1240,
    rat: 100,
    terceiros: 100,
    total_proventos: 5500,
    total_descontos: 880,
    salario_liquido: 4620,
    status: 'ACTIVE',
    address: { zipCode: '01310-000', street: 'Rua Augusta', number: '250', neighborhood: 'Consolação', city: 'São Paulo', state: 'SP' }
  },
  { 
    id: 'p4', 
    unitId: 'u-filial1',
    matricula: '2024004', 
    employeeName: 'Bruno Henrique Souza', 
    cpf: '555.666.777-88',
    rg: '55.666.777-8',
    pis: '150.77889.00-1',
    ctps: '0087654/0004',
    cargo: 'Auxiliar de Som',
    funcao: 'Operação de Áudio',
    departamento: 'Louvor',
    cbo: '3741-05',
    data_admissao: '2023-02-10',
    birthDate: '1998-04-22',
    tipo_contrato: 'CLT',
    jornada_trabalho: '36h semanais',
    regime_trabalho: 'PRESENCIAL',
    salario_base: 2200,
    tipo_salario: 'MENSAL',
    he50_qtd: 6,
    he100_qtd: 0,
    dsr_ativo: true,
    adic_noturno_qtd: 0,
    insalubridade_grau: 'LOW',
    periculosidade_ativo: false,
    comissoes: 0,
    gratificacoes: 100,
    premios: 0,
    ats_percentual: 1,
    auxilio_moradia: 0,
    arredondamento: 0,
    dependentes_qtd: 0,
    dependentes_lista: [],
    is_pcd: false,
    tipo_deficiencia: '',
    blood_type: 'A-',
    emergency_contact: '(11) 98888-1111 (Pai)',
    vt_ativo: true,
    vale_transporte_total: 160,
    va_ativo: false,
    vale_alimentacao: 0,
    vr_ativo: true,
    vale_refeicao: 280,
    ps_ativo: false,
    plano_saude_colaborador: 0,
    po_ativo: false,
    plano_saude_dependentes: 0,
    vale_farmacia: 0,
    seguro_vida: 15,
    banco: 'Bradesco',
    codigo_banco: '237',
    agencia: '7777',
    conta: '99999-1',
    tipo_conta: 'CORRENTE',
    titular: 'Bruno Henrique Souza',
    chave_pix: '555.666.777-88',
    month: '05',
    year: '2024',
    faltas: 0,
    atrasos: 0,
    adiantamento: 0,
    pensao_alimenticia: 0,
    consignado: 0,
    outros_descontos: 0,
    coparticipacoes: 0,
    inss: 180.00,
    fgts_retido: 176,
    irrf: 0,
    fgts_patronal: 176,
    inss_patronal: 440,
    rat: 66,
    terceiros: 66,
    total_proventos: 2400,
    total_descontos: 180,
    salario_liquido: 2220,
    status: 'ACTIVE',
    address: { zipCode: '08090-200', street: 'Rua Itaquera', number: '800', neighborhood: 'Leste', city: 'São Paulo', state: 'SP' }
  },
  { 
    id: 'p5', 
    unitId: 'u-sede',
    matricula: '2024005', 
    employeeName: 'Fernanda Carvalho', 
    cpf: '666.777.888-99',
    rg: '66.777.888-9',
    pis: '160.88990.11-2',
    ctps: '0098765/0005',
    cargo: 'Coordenadora de Comunicação',
    funcao: 'Comunicação',
    departamento: 'Administrativo',
    cbo: '2611-05',
    data_admissao: '2019-11-05',
    birthDate: '1987-12-05',
    tipo_contrato: 'CLT',
    jornada_trabalho: '40h semanais',
    regime_trabalho: 'HIBRIDO',
    salario_base: 4800,
    tipo_salario: 'MENSAL',
    he50_qtd: 4,
    he100_qtd: 0,
    dsr_ativo: true,
    adic_noturno_qtd: 0,
    insalubridade_grau: 'NONE',
    periculosidade_ativo: false,
    comissoes: 0,
    gratificacoes: 200,
    premios: 0,
    ats_percentual: 2,
    auxilio_moradia: 0,
    arredondamento: 0,
    dependentes_qtd: 0,
    dependentes_lista: [],
    is_pcd: false,
    tipo_deficiencia: '',
    blood_type: 'AB+',
    emergency_contact: '(11) 95555-2222 (Irmã)',
    vt_ativo: true,
    vale_transporte_total: 180,
    va_ativo: true,
    vale_alimentacao: 600,
    vr_ativo: true,
    vale_refeicao: 300,
    ps_ativo: true,
    plano_saude_colaborador: 320,
    po_ativo: false,
    plano_saude_dependentes: 0,
    vale_farmacia: 40,
    seguro_vida: 22,
    banco: 'Itaú',
    codigo_banco: '341',
    agencia: '0303',
    conta: '34567-8',
    tipo_conta: 'CORRENTE',
    titular: 'Fernanda Carvalho',
    chave_pix: 'fernanda@adjpa.org',
    month: '05',
    year: '2024',
    faltas: 0,
    atrasos: 0,
    adiantamento: 0,
    pensao_alimenticia: 0,
    consignado: 0,
    outros_descontos: 0,
    coparticipacoes: 0,
    inss: 560.00,
    fgts_retido: 384,
    irrf: 80.00,
    fgts_patronal: 384,
    inss_patronal: 1120,
    rat: 96,
    terceiros: 96,
    total_proventos: 5000,
    total_descontos: 702,
    salario_liquido: 4298,
    status: 'ACTIVE',
    address: { zipCode: '04004-020', street: 'Rua Domingos de Morais', number: '1500', neighborhood: 'Vila Mariana', city: 'São Paulo', state: 'SP' }
  },
  { 
    id: 'p6', 
    unitId: 'u-filial1',
    matricula: '2024006', 
    employeeName: 'Marcos Vinícius Pereira', 
    cpf: '777.888.999-00',
    rg: '77.888.999-0',
    pis: '170.99011.22-3',
    ctps: '0109876/0006',
    cargo: 'Coordenador de Eventos',
    funcao: 'Organização de Eventos',
    departamento: 'Eventos',
    cbo: '1221-05',
    data_admissao: '2024-01-20',
    birthDate: '1991-03-14',
    tipo_contrato: 'CLT',
    jornada_trabalho: '36h semanais',
    regime_trabalho: 'PRESENCIAL',
    salario_base: 3000,
    tipo_salario: 'MENSAL',
    he50_qtd: 5,
    he100_qtd: 2,
    dsr_ativo: true,
    adic_noturno_qtd: 0,
    insalubridade_grau: 'NONE',
    periculosidade_ativo: false,
    comissoes: 0,
    gratificacoes: 150,
    premios: 0,
    ats_percentual: 1,
    auxilio_moradia: 0,
    arredondamento: 0,
    dependentes_qtd: 0,
    dependentes_lista: [],
    is_pcd: false,
    tipo_deficiencia: '',
    blood_type: 'O-',
    emergency_contact: '(11) 93333-4444 (Esposa)',
    vt_ativo: true,
    vale_transporte_total: 200,
    va_ativo: true,
    vale_alimentacao: 450,
    vr_ativo: true,
    vale_refeicao: 320,
    ps_ativo: true,
    plano_saude_colaborador: 280,
    po_ativo: false,
    plano_saude_dependentes: 0,
    vale_farmacia: 30,
    seguro_vida: 18,
    banco: 'Santander',
    codigo_banco: '033',
    agencia: '5555',
    conta: '88888-2',
    tipo_conta: 'CORRENTE',
    titular: 'Marcos Vinícius Pereira',
    chave_pix: '777.888.999-00',
    month: '05',
    year: '2024',
    faltas: 0,
    atrasos: 0,
    adiantamento: 0,
    pensao_alimenticia: 0,
    consignado: 0,
    outros_descontos: 0,
    coparticipacoes: 0,
    inss: 320.00,
    fgts_retido: 240,
    irrf: 0,
    fgts_patronal: 240,
    inss_patronal: 800,
    rat: 72,
    terceiros: 72,
    total_proventos: 3150,
    total_descontos: 320,
    salario_liquido: 2830,
    status: 'ACTIVE',
    address: { zipCode: '08230-000', street: 'Rua São Teodoro', number: '220', neighborhood: 'Itaquera', city: 'São Paulo', state: 'SP' }
  }
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  { id: 't1', unitId: 'u-sede', description: 'Dízimo João Silva', amount: 500, date: '2024-05-01', competencyDate: '2024-05-01', type: 'INCOME', category: 'TITHE', costCenter: 'cc1', accountId: 'acc2', memberId: '1', status: 'PAID', isConciliated: true, operationNature: 'nat6' },
  { id: 't2', unitId: 'u-sede', description: 'Energia Elétrica Templo', amount: 850, date: '2024-05-10', competencyDate: '2024-05-10', type: 'EXPENSE', category: 'UTILITIES', costCenter: 'cc1', accountId: 'acc2', status: 'PAID', isConciliated: true, operationNature: 'nat1' },
  { id: 't3', unitId: 'u-sede', description: 'Oferta Culto de Domingo', amount: 1200, date: '2024-05-12', competencyDate: '2024-05-12', type: 'INCOME', category: 'OFFERING', costCenter: 'cc2', accountId: 'acc1', status: 'PAID', isConciliated: true, operationNature: 'nat6' },
  { id: 't4', unitId: 'u-filial1', description: 'Aluguel Unidade Leste', amount: 3500, date: '2024-05-05', competencyDate: '2024-05-05', type: 'EXPENSE', category: 'RENT', costCenter: 'cc1', accountId: 'acc3', status: 'PAID', isConciliated: true, operationNature: 'nat1' },
  { id: 't5', unitId: 'u-sede', description: 'Compra de Som - Microfones', amount: 2800, date: '2024-05-15', competencyDate: '2024-05-15', type: 'EXPENSE', category: 'EQUIPMENT', costCenter: 'cc4', accountId: 'acc2', status: 'PAID', isConciliated: true, operationNature: 'nat2' },
  { id: 't13', unitId: 'u-sede', description: 'Dízimo João Silva', amount: 480, date: '2024-01-07', competencyDate: '2024-01-07', type: 'INCOME', category: 'TITHE', costCenter: 'cc1', accountId: 'acc2', memberId: '1', status: 'PAID', isConciliated: true, operationNature: 'nat6' },
  { id: 't14', unitId: 'u-sede', description: 'Oferta Culto de Domingo', amount: 1000, date: '2024-01-14', competencyDate: '2024-01-14', type: 'INCOME', category: 'OFFERING', costCenter: 'cc2', accountId: 'acc1', status: 'PAID', isConciliated: true, operationNature: 'nat6' },
  { id: 't15', unitId: 'u-filial1', description: 'Aluguel Unidade Leste', amount: 3500, date: '2024-01-05', competencyDate: '2024-01-05', type: 'EXPENSE', category: 'RENT', costCenter: 'cc1', accountId: 'acc3', status: 'PAID', isConciliated: true, operationNature: 'nat1' },
  { id: 't16', unitId: 'u-sede', description: 'Internet Administrativo', amount: 820, date: '2024-01-20', competencyDate: '2024-01-20', type: 'EXPENSE', category: 'UTILITIES', costCenter: 'cc1', accountId: 'acc2', status: 'PAID', isConciliated: true, operationNature: 'nat1' },
  { id: 't17', unitId: 'u-sede', description: 'Dízimo João Silva', amount: 500, date: '2024-02-04', competencyDate: '2024-02-04', type: 'INCOME', category: 'TITHE', costCenter: 'cc1', accountId: 'acc2', memberId: '1', status: 'PAID', isConciliated: true, operationNature: 'nat6' },
  { id: 't18', unitId: 'u-sede', description: 'Oferta Culto de Domingo', amount: 950, date: '2024-02-11', competencyDate: '2024-02-11', type: 'INCOME', category: 'OFFERING', costCenter: 'cc2', accountId: 'acc1', status: 'PAID', isConciliated: true, operationNature: 'nat6' },
  { id: 't19', unitId: 'u-filial1', description: 'Aluguel Unidade Leste', amount: 3500, date: '2024-02-05', competencyDate: '2024-02-05', type: 'EXPENSE', category: 'RENT', costCenter: 'cc1', accountId: 'acc3', status: 'PAID', isConciliated: true, operationNature: 'nat1' },
  { id: 't20', unitId: 'u-sede', description: 'Internet Administrativo', amount: 830, date: '2024-02-19', competencyDate: '2024-02-19', type: 'EXPENSE', category: 'UTILITIES', costCenter: 'cc1', accountId: 'acc2', status: 'PAID', isConciliated: true, operationNature: 'nat1' },
  { id: 't21', unitId: 'u-sede', description: 'Dízimo Maria Oliveira', amount: 450, date: '2024-03-03', competencyDate: '2024-03-03', type: 'INCOME', category: 'TITHE', costCenter: 'cc1', accountId: 'acc2', memberId: '2', status: 'PAID', isConciliated: true, operationNature: 'nat6' },
  { id: 't22', unitId: 'u-sede', description: 'Oferta Culto de Domingo', amount: 1100, date: '2024-03-10', competencyDate: '2024-03-10', type: 'INCOME', category: 'OFFERING', costCenter: 'cc2', accountId: 'acc1', status: 'PAID', isConciliated: true, operationNature: 'nat6' },
  { id: 't23', unitId: 'u-filial1', description: 'Aluguel Unidade Leste', amount: 3500, date: '2024-03-05', competencyDate: '2024-03-05', type: 'EXPENSE', category: 'RENT', costCenter: 'cc1', accountId: 'acc3', status: 'PAID', isConciliated: true, operationNature: 'nat1' },
  { id: 't24', unitId: 'u-sede', description: 'Internet Administrativo', amount: 840, date: '2024-03-18', competencyDate: '2024-03-18', type: 'EXPENSE', category: 'UTILITIES', costCenter: 'cc1', accountId: 'acc2', status: 'PAID', isConciliated: true, operationNature: 'nat1' },
  { id: 't25', unitId: 'u-sede', description: 'Dízimo João Silva', amount: 520, date: '2024-04-07', competencyDate: '2024-04-07', type: 'INCOME', category: 'TITHE', costCenter: 'cc1', accountId: 'acc2', memberId: '1', status: 'PAID', isConciliated: true, operationNature: 'nat6' },
  { id: 't26', unitId: 'u-sede', description: 'Oferta Culto de Domingo', amount: 1150, date: '2024-04-14', competencyDate: '2024-04-14', type: 'INCOME', category: 'OFFERING', costCenter: 'cc2', accountId: 'acc1', status: 'PAID', isConciliated: true, operationNature: 'nat6' },
  { id: 't27', unitId: 'u-filial1', description: 'Aluguel Unidade Leste', amount: 3500, date: '2024-04-05', competencyDate: '2024-04-05', type: 'EXPENSE', category: 'RENT', costCenter: 'cc1', accountId: 'acc3', status: 'PAID', isConciliated: true, operationNature: 'nat1' },
  { id: 't28', unitId: 'u-sede', description: 'Internet Administrativo', amount: 845, date: '2024-04-20', competencyDate: '2024-04-20', type: 'EXPENSE', category: 'UTILITIES', costCenter: 'cc1', accountId: 'acc2', status: 'PAID', isConciliated: true, operationNature: 'nat1' },
  { id: 't29', unitId: 'u-sede', description: 'Compra de Cabos de Áudio', amount: 1500, date: '2024-04-25', competencyDate: '2024-04-25', type: 'EXPENSE', category: 'EQUIPMENT', costCenter: 'cc4', accountId: 'acc2', status: 'PAID', isConciliated: true, operationNature: 'nat2' },
  { id: 't6', unitId: 'u-sede', description: 'Dízimo Ana Paula Martins', amount: 650, date: '2024-06-02', competencyDate: '2024-06-02', type: 'INCOME', category: 'TITHE', costCenter: 'cc1', accountId: 'acc2', memberId: '4', status: 'PAID', isConciliated: true, operationNature: 'nat6' },
  { id: 't7', unitId: 'u-sede', description: 'Oferta Ana Paula Martins', amount: 100, date: '2024-06-16', competencyDate: '2024-06-16', type: 'INCOME', category: 'OFFERING', costCenter: 'cc2', accountId: 'acc1', memberId: '4', status: 'PAID', isConciliated: true, operationNature: 'nat6' },
  { id: 't8', unitId: 'u-filial1', description: 'Oferta Bruno Henrique', amount: 120, date: '2024-06-09', competencyDate: '2024-06-09', type: 'INCOME', category: 'OFFERING', costCenter: 'cc2', accountId: 'acc3', memberId: '5', status: 'PAID', isConciliated: true, operationNature: 'nat6' },
  { id: 't9', unitId: 'u-sede', description: 'Dízimo Fernanda Carvalho', amount: 400, date: '2024-06-08', competencyDate: '2024-06-08', type: 'INCOME', category: 'TITHE', costCenter: 'cc1', accountId: 'acc2', memberId: '6', status: 'PAID', isConciliated: true, operationNature: 'nat6' },
  { id: 't10', unitId: 'u-sede', description: 'Internet Administrativo', amount: 320, date: '2024-06-05', competencyDate: '2024-06-05', type: 'EXPENSE', category: 'UTILITIES', costCenter: 'cc1', accountId: 'acc2', status: 'PAID', isConciliated: true, operationNature: 'nat1' },
  { id: 't11', unitId: 'u-filial1', description: 'Manutenção Equipamentos de Som', amount: 540, date: '2024-06-18', competencyDate: '2024-06-18', type: 'EXPENSE', category: 'EQUIPMENT', costCenter: 'cc4', accountId: 'acc3', status: 'PAID', isConciliated: true, operationNature: 'nat2' },
  { id: 't12', unitId: 'u-sede', description: 'Projeto Social Mãos Amigas - Doação', amount: 900, date: '2024-06-22', competencyDate: '2024-06-22', type: 'INCOME', category: 'DONATION', costCenter: 'cc6', projectId: 'prj4', accountId: 'acc1', status: 'PAID', isConciliated: true, operationNature: 'nat7' }
];

export const MOCK_AUDIT: AuditLog[] = [
  { id: 'a1', unitId: 'u-sede', userId: 'u1', userName: 'Anderson Lima', action: 'CREATE_PAYROLL', entity: 'Payroll', date: '2024-05-15 14:30', ip: '127.0.0.1' },
];

export const MOCK_EVENTS: ChurchEvent[] = [
  {
    id: 'e1',
    unitId: 'u-sede',
    title: 'Culto de Celebração',
    description: 'Culto dominical com louvor e palavra de esperança.',
    date: '2024-06-19',
    time: '18:00',
    location: 'Templo Sede',
    attendeesCount: 250,
    type: 'SERVICE'
  }
];
